from .ccd_models import *
from .depositos_models import *
from .expedientes_models import *
from .metadatos_models import *
from .permisos_models import *
from .radicados_models import *
from .tca_models import *
from .trd_models import *
from .encuencas_models import *
from .plantillas_models import *
from .configuracion_tiempos_respuesta_models import *
from .conf__tipos_exp_models import *
from .bandeja_tareas_models import *
from .transferencias_documentales_models import *
from .consecutivo_unidad_models import *