tipo_doc_ultimo_CHOICES = (
    ('E_CPR', 'ENTRADA_COMPRA'),
    ('E_DON', 'ENTRADA_DONACIÓN'),
    ('E_RES', 'ENTRADA_RESARCIMIENTO'),
    ('E_CPS', 'ENTRADA_COMPENSACION'),
    ('E_CMD', 'ENTRADA_COMODATO'),
    ('E_CNV', 'ENTRADA_CONVENIO'),
    ('E_EMB', 'ENTRADA_EMBARGO'),
    ('E_INC', 'ENTRADA_INCAUTACION'),
    ('E_APR', 'ENTRADA_APROPIACION'),
    ('ASIG', 'ASIGNACIÓN'),
    ('REAS', 'REASIGNACIÓN'),
    ('DEV_A', 'DEVOLUCIÓN DE ASIGNADO'),
    ('PRES', 'PRESTAMO'),
    ('DEV_P', 'DEVOLUCIÓN DE PRESTADO'),
    ('MANT', 'MANTENIMIENTO'),
    ('BAJA', 'BAJA'),
    ('SAL_E', 'SALIDA ESPECIAL')
)