version: '3.8'

services: # the different images that will be running as containers

  db: # service name
    # image name of the postgres database. during build, this will be pulled from dockerhub and a container spun up from it.
    image: postgres:14-alpine 
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    # access credentials from the .env file
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=bia
    ports:
      - 5435:5432
    # networks:
    #   - db_network
    restart: "on-failure"

  db_estaciones: # service name
    # image name of the postgres database. during build, this will be pulled from dockerhub and a container spun up from it.
    image: postgres:14-alpine 
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data_estaciones:/var/lib/postgresql/data/
    # access credentials from the .env file
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=bia_estaciones
    ports:
      - 5436:5432
    # networks:
    #   - db_network
    restart: "on-failure"

volumes:
  postgres_data:
  postgres_data_estaciones:

# networks:
#   db_network:
#     driver: bridge