# Generated by Django 4.1.3 on 2022-12-30 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0002_initial'),
        ('seguridad', '0001_initial'),
        ('conservacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivero',
            name='id_persona_abre',
            field=models.ForeignKey(blank=True, db_column='T150Id_PersonaAbre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_abre_vivero', to='seguridad.personas'),
        ),
        migrations.AddField(
            model_name='vivero',
            name='id_persona_cierra',
            field=models.ForeignKey(blank=True, db_column='T150Id_PersonaCierra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_cierra_vivero', to='seguridad.personas'),
        ),
        migrations.AddField(
            model_name='vivero',
            name='id_persona_crea',
            field=models.ForeignKey(db_column='T150Id_PersonaCrea', on_delete=django.db.models.deletion.CASCADE, related_name='persona_crea_vivero', to='seguridad.personas'),
        ),
        migrations.AddField(
            model_name='vivero',
            name='id_persona_cuarentena',
            field=models.ForeignKey(blank=True, db_column='T150Id_PersonaCuarentena', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_cuarentena_vivero', to='seguridad.personas'),
        ),
        migrations.AddField(
            model_name='vivero',
            name='id_viverista_actual',
            field=models.ForeignKey(blank=True, db_column='T150Id_ViveristaActual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_persona_viverista_actual', to='seguridad.personas'),
        ),
        migrations.AddField(
            model_name='itemsdespachoentrante',
            name='id_bien',
            field=models.ForeignKey(db_column='T154Id_Bien', on_delete=django.db.models.deletion.CASCADE, to='almacen.catalogobienes'),
        ),
        migrations.AddField(
            model_name='itemsdespachoentrante',
            name='id_despacho_entrante',
            field=models.ForeignKey(db_column='T154Id_DespachoEntrante', on_delete=django.db.models.deletion.CASCADE, to='conservacion.despachoentrantes'),
        ),
        migrations.AddField(
            model_name='itemsdespachoentrante',
            name='id_entrada_alm_del_bien',
            field=models.ForeignKey(blank=True, db_column='T154Id_EntradaAlmDelBien', null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.entradasalmacen'),
        ),
        migrations.AddField(
            model_name='inventarioviveros',
            name='cod_tipo_entrada_lote',
            field=models.ForeignKey(blank=True, db_column='T156cod_TipoEntradaLote', null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.tiposentradas'),
        ),
        migrations.AddField(
            model_name='inventarioviveros',
            name='id_bien',
            field=models.ForeignKey(db_column='T156Id_Bien', on_delete=django.db.models.deletion.CASCADE, to='almacen.catalogobienes'),
        ),
        migrations.AddField(
            model_name='inventarioviveros',
            name='id_vivero',
            field=models.ForeignKey(db_column='T156Id_Vivero', on_delete=django.db.models.deletion.CASCADE, to='conservacion.vivero'),
        ),
        migrations.AddField(
            model_name='historialcuarentenaviveros',
            name='id_persona_finaliza_cuarentena',
            field=models.ForeignKey(db_column='T152Id_PersonaFinalizaCuarentena', on_delete=django.db.models.deletion.CASCADE, related_name='persona_finaliza_cuarentena', to='seguridad.personas'),
        ),
        migrations.AddField(
            model_name='historialcuarentenaviveros',
            name='id_persona_inicia_cuarentena',
            field=models.ForeignKey(db_column='T152Id_PersonaIniciaCuarentena', on_delete=django.db.models.deletion.CASCADE, related_name='persona_inicia_cuarentena', to='seguridad.personas'),
        ),
        migrations.AddField(
            model_name='historialcuarentenaviveros',
            name='id_vivero',
            field=models.ForeignKey(db_column='T152Id_Vivero', on_delete=django.db.models.deletion.CASCADE, to='conservacion.vivero'),
        ),
        migrations.AddField(
            model_name='historialaperturaviveros',
            name='id_persona_apertura_anterior',
            field=models.ForeignKey(db_column='T151Id_PersonaAperturaAnterior', on_delete=django.db.models.deletion.CASCADE, related_name='persona_apertura_anterior', to='seguridad.personas'),
        ),
        migrations.AddField(
            model_name='historialaperturaviveros',
            name='id_persona_cierre_correspondiente',
            field=models.ForeignKey(db_column='T151Id_PersonaCierreCorrespondiente', on_delete=django.db.models.deletion.CASCADE, related_name='persona_cierre_correspondiente', to='seguridad.personas'),
        ),
        migrations.AddField(
            model_name='historialaperturaviveros',
            name='id_vivero',
            field=models.ForeignKey(db_column='T151Id_Vivero', on_delete=django.db.models.deletion.CASCADE, to='conservacion.vivero'),
        ),
        migrations.AddField(
            model_name='distribucionesitemdespachoentrante',
            name='id_item_despacho_entrante',
            field=models.ForeignKey(db_column='T155IdItem_DespachoEntrante', on_delete=django.db.models.deletion.CASCADE, to='conservacion.itemsdespachoentrante'),
        ),
        migrations.AddField(
            model_name='distribucionesitemdespachoentrante',
            name='id_vivero',
            field=models.ForeignKey(db_column='T155Id_Vivero', on_delete=django.db.models.deletion.CASCADE, to='conservacion.vivero'),
        ),
        migrations.AddField(
            model_name='despachoentrantes',
            name='id_despacho_consumo_alm',
            field=models.ForeignKey(db_column='T153Id_DespachoConsumoAlm', on_delete=django.db.models.deletion.CASCADE, to='almacen.despachoconsumo'),
        ),
        migrations.AddField(
            model_name='despachoentrantes',
            name='id_persona_distribuye',
            field=models.ForeignKey(blank=True, db_column='T153Id_PersonaDistribuye', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.personas'),
        ),
        migrations.AlterUniqueTogether(
            name='itemsdespachoentrante',
            unique_together={('id_despacho_entrante', 'id_bien', 'id_entrada_alm_del_bien')},
        ),
        migrations.AlterUniqueTogether(
            name='inventarioviveros',
            unique_together={('id_vivero', 'id_bien', 'agno_lote', 'nro_lote', 'cod_etapa_lote')},
        ),
        migrations.AlterUniqueTogether(
            name='distribucionesitemdespachoentrante',
            unique_together={('id_item_despacho_entrante', 'id_vivero')},
        ),
    ]
