# Generated by Django 4.1.3 on 2022-12-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivero',
            name='fecha_inicio_cuarentena',
            field=models.DateTimeField(blank=True, db_column='T150fechaInicioCuarentena', null=True),
        ),
    ]
