# Generated by Django 4.1.3 on 2022-12-05 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='es_unidad_organizacional_actual',
            field=models.BooleanField(blank=True, db_column='T010esUnidadDeOrganigramaActual', null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='fecha_asignacion_unidad',
            field=models.DateTimeField(blank=True, db_column='T010fechaAsignacionUnidadOrg', null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='id_cargo',
            field=models.ForeignKey(blank=True, db_column='T010Id_Cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.cargos'),
        ),
        migrations.AddField(
            model_name='personas',
            name='id_unidad_organizacional_actual',
            field=models.ForeignKey(blank=True, db_column='T010Id_UnidadOrganizacionalActual', null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.unidadesorganizacionales'),
        ),
    ]
