# Generated by Django 4.1.3 on 2022-12-06 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_entradasalmacen_itementradaalmacen'),
        ('seguridad', '0002_personas_es_unidad_organizacional_actual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoUnidadesOrgPersona',
            fields=[
                ('id_historico_unidad_persona', models.AutoField(db_column='T020IdHistoUnidad_Persona', editable=False, primary_key=True, serialize=False)),
                ('justificacion_cambio', models.CharField(db_column='T020justificacionDelCambio', max_length=255)),
                ('fecha_inicio', models.DateTimeField(db_column='T020fechaInicio')),
                ('fecha_final', models.DateTimeField(db_column='T020fechaFinal')),
                ('id_persona', models.ForeignKey(db_column='T020Id_Persona', on_delete=django.db.models.deletion.CASCADE, to='seguridad.personas')),
                ('id_unidad_organizacional', models.ForeignKey(db_column='T020Id_UnidadOrganizativa', on_delete=django.db.models.deletion.CASCADE, to='almacen.unidadesorganizacionales')),
            ],
            options={
                'verbose_name': 'Historico Unidad Org Persona',
                'verbose_name_plural': 'Historicos Unidades org Personas',
                'db_table': 'T020HistoricoUnidadesOrg_Persona',
            },
        ),
    ]
