# Generated by Django 4.1.3 on 2022-12-12 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documental', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clasif_serie_subserie_unidad_tca',
            old_name='cod_clas_expediente',
            new_name='expediente',
        ),
    ]
