# Generated by Django 4.1.3 on 2022-12-12 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documental', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CCD_Clasif_Serie_Subserie_TCA',
            new_name='Clasif_Serie_Subserie_Unidad_TCA',
        ),
        migrations.AlterField(
            model_name='clasif_serie_subserie_unidad_tca',
            name='cod_clas_expediente',
            field=models.ForeignKey(db_column='T215Cod_ClasificacionExp', on_delete=django.db.models.deletion.CASCADE, to='gestion_documental.clasificacionexpedientes'),
        ),
    ]
