# Generated by Django 4.1.3 on 2022-12-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documental', '0003_rename_ccd_clasif_serie_subserie_tca_clasif_serie_subserie_unidad_tca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasif_serie_subserie_unidad_tca',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, db_column='T215fechaRegistro'),
        ),
    ]
