# Generated by Django 4.1.3 on 2022-12-06 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_personas_es_unidad_organizacional_actual_and_more'),
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradasAlmacen',
            fields=[
                ('id_entrada_almacen', models.AutoField(db_column='T063IdEntradaAlmacen', editable=False, primary_key=True, serialize=False)),
                ('numero_entrada_almacen', models.PositiveIntegerField(db_column='T063nroEntradaAlmacen')),
                ('fecha_entrada', models.DateTimeField(db_column='T063fechaEntrada')),
                ('fecha_real_registro', models.DateTimeField(auto_now=True, db_column='T063fechaRealRegistro')),
                ('motivo', models.CharField(db_column='T063motivo', max_length=255)),
                ('observacion', models.CharField(blank=True, db_column='T063observacion', max_length=255, null=True)),
                ('valor_total_entrada', models.DecimalField(db_column='T063valorTotalEntrada', decimal_places=2, max_digits=12)),
                ('fecha_ultima_actualizacion_diferente_creador', models.DateTimeField(blank=True, db_column='T063fechaUltActualizacionDifACrea', null=True)),
                ('entrada_anulada', models.BooleanField(blank=True, db_column='T063entradaAnulada', null=True)),
                ('justificacion_anulacion', models.CharField(blank=True, db_column='T063justificacionAnulacion', max_length=255, null=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, db_column='T063fechaAnulacion', null=True)),
                ('id_bodega', models.ForeignKey(db_column='T063Id_BodegaGral', on_delete=django.db.models.deletion.CASCADE, to='almacen.bodegas')),
                ('id_creador', models.ForeignKey(db_column='T063Id_PersonaCrea', on_delete=django.db.models.deletion.CASCADE, related_name='persona_crea_entrada', to='seguridad.personas')),
                ('id_persona_anula', models.ForeignKey(blank=True, db_column='T063Id_PersonaAnula', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_anula_entrada', to='seguridad.personas')),
                ('id_persona_ult_act_dif_creador', models.ForeignKey(blank=True, db_column='T063Id_PersonaUltActualizacionDifACrea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_actualiza_entrada', to='seguridad.personas')),
                ('id_proveedor', models.ForeignKey(db_column='T063Id_Proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='persona_provee_entrada', to='seguridad.personas')),
                ('id_tipo_entrada', models.ForeignKey(db_column='T063Cod_TipoEntrada', on_delete=django.db.models.deletion.CASCADE, to='almacen.tiposentradas')),
            ],
            options={
                'verbose_name': 'Entrada de Almacen',
                'verbose_name_plural': 'Entradas de Almacen',
                'db_table': 'T063EntradasAlmacen',
            },
        ),
        migrations.CreateModel(
            name='ItemEntradaAlmacen',
            fields=[
                ('id_item_entrada_almacen', models.AutoField(db_column='T064IdItem_EntradaAlmacen', editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(db_column='T064cantidad')),
                ('valor_unitario', models.DecimalField(db_column='T064valorUnitario', decimal_places=2, max_digits=9)),
                ('porcentaje_iva', models.DecimalField(db_column='T064porcentajeIVA', decimal_places=2, max_digits=3)),
                ('valor_iva', models.DecimalField(db_column='T064valorIVA', decimal_places=2, max_digits=9)),
                ('valor_total_item', models.DecimalField(db_column='T064valorTotalItem', decimal_places=2, max_digits=9)),
                ('cod_estado', models.CharField(choices=[('O', 'Óptimo'), ('D', 'Defectuoso'), ('A', 'Averiado')], db_column='T064Cod_Estado', max_length=1)),
                ('doc_identificador_bien', models.CharField(blank=True, db_column='T064docIdentificadorBien', max_length=30, null=True)),
                ('cantidad_vida_util', models.PositiveSmallIntegerField(blank=True, db_column='T064cantidadVidaUtil', null=True)),
                ('valor_residual', models.DecimalField(blank=True, db_column='T064valorResidual', decimal_places=0, max_digits=10, null=True)),
                ('numero_posicion', models.PositiveSmallIntegerField(db_column='T064nroPosicion')),
                ('id_bien', models.ForeignKey(db_column='T064Id_Bien', on_delete=django.db.models.deletion.CASCADE, to='almacen.catalogobienes')),
                ('id_bodega', models.ForeignKey(db_column='T064Id_Bodega', on_delete=django.db.models.deletion.CASCADE, to='almacen.bodegas')),
                ('id_entrada_almacen', models.ForeignKey(db_column='T064Id_EntradaAlmacen', on_delete=django.db.models.deletion.CASCADE, to='almacen.entradasalmacen')),
                ('id_unidad_medida_vida_util', models.ForeignKey(blank=True, db_column='T064Id_UnidadMedidaVidaUtil', null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.unidadesmedida')),
            ],
            options={
                'verbose_name': 'Tipo entrada de Almacen',
                'verbose_name_plural': 'Tipos de Entradas de Almacen',
                'db_table': 'T064Items_EntradaAlmacen',
            },
        ),
    ]
