# Generated by Django 4.1.1 on 2022-11-28 21:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposactivo',
            name='cod_tipo_activo',
            field=models.CharField(choices=[('Com', 'Computador'), ('Veh', 'Vehículo'), ('OAc', 'Otros Activos'), ('Ter', 'Terrenos'), ('CyE', 'Construcciones y Edificaciones'), ('Int', 'Intangibles')], db_column='T060CodTipoActivo', max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tiposactivo',
            name='nombre',
            field=models.CharField(db_column='T060nombre', max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='CatalogoBienes',
            fields=[
                ('id_bien', models.AutoField(db_column='T057IdBien', primary_key=True, serialize=False)),
                ('codigo_bien', models.CharField(db_column='T057codigoBien', max_length=12)),
                ('nro_elemento_bien', models.PositiveSmallIntegerField(blank=True, db_column='T057nroElementoEnElBien', null=True)),
                ('nombre', models.CharField(db_column='T057nombre', max_length=100)),
                ('cod_tipo_bien', models.CharField(choices=[('A', 'Activo Fijo'), ('C', 'Consumo')], db_column='T057codTipoBien', max_length=1)),
                ('cod_tipo_activo', models.CharField(blank=True, choices=[('Com', 'Computador'), ('Veh', 'Vehículo'), ('OAc', 'Otros Activos'), ('Ter', 'Terrenos'), ('CyE', 'Construcciones y Edificaciones'), ('Int', 'Intangibles')], db_column='T057Cod_TipoActivo', max_length=3, null=True)),
                ('nivel_jerarquico', models.PositiveSmallIntegerField(db_column='T057nivelJerarquico', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('nombre_cientifico', models.CharField(blank=True, db_column='T057nombreCientifico', max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='T057descripcion', max_length=255, null=True)),
                ('doc_identificador_nro', models.CharField(blank=True, db_column='T057docIdentificadorNro', max_length=30, null=True)),
                ('cod_metodo_valoracion', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Promedio Ponderado'), (2, 'PEPS'), (3, 'UEPS')], db_column='T057Cod_MetodoValoracion', null=True)),
                ('cod_tipo_depreciacion', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Línea Recta'), (2, 'Segunda Opción')], db_column='T057Cod_TipoDepreciacion', null=True)),
                ('cantidad_vida_util', models.PositiveSmallIntegerField(blank=True, db_column='T057cantidadVidaUtil', null=True)),
                ('valor_residual', models.FloatField(blank=True, db_column='T057valorResidual', null=True)),
                ('stock_minimo', models.PositiveSmallIntegerField(blank=True, db_column='T057stockMinimo', null=True)),
                ('stock_maximo', models.PositiveIntegerField(blank=True, db_column='T057stockMaximo', null=True)),
                ('solicitable_vivero', models.BooleanField(db_column='T057solicitablePorVivero', default=False)),
                ('tiene_hoja_vida', models.BooleanField(blank=True, db_column='T057tieneHojaDeVida', null=True)),
                ('maneja_hoja_vida', models.BooleanField(db_column='T057manejaHojaDeVida', default=False)),
                ('visible_solicitudes', models.BooleanField(db_column='T057visibleEnSolicitudes', default=False)),
                ('id_bien_padre', models.ForeignKey(blank=True, db_column='T057Id_BienPadre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.catalogobienes')),
                ('id_marca', models.ForeignKey(blank=True, db_column='T057Id_Marca', null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.marcas')),
                ('id_porcentaje_iva', models.ForeignKey(db_column='T057Id_PorcentajeIVA', on_delete=django.db.models.deletion.CASCADE, to='almacen.porcentajesiva')),
                ('id_unidad_medida', models.ForeignKey(db_column='T057Id_UnidadMedida', on_delete=django.db.models.deletion.CASCADE, related_name='unidad_medida', to='almacen.unidadesmedida')),
                ('id_unidad_medida_vida_util', models.ForeignKey(blank=True, db_column='T057Id_UnidadMedidaVidaUtil', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidad_medida_vida_util', to='almacen.unidadesmedida')),
            ],
            options={
                'verbose_name': 'Catalogo Bien',
                'verbose_name_plural': 'Catalogo Bienes',
                'db_table': 'T057CatalogoBienes',
                'unique_together': {('codigo_bien', 'nro_elemento_bien')},
            },
        ),
        migrations.AlterField(
            model_name='documentosvehiculo',
            name='id_articulo',
            field=models.ForeignKey(db_column='T068Id_Articulo', on_delete=django.db.models.deletion.CASCADE, to='almacen.catalogobienes'),
        ),
        migrations.AlterField(
            model_name='hojadevidacomputadores',
            name='id_articulo',
            field=models.ForeignKey(db_column='T065Id_Articulo', on_delete=django.db.models.deletion.CASCADE, to='almacen.catalogobienes'),
        ),
        migrations.AlterField(
            model_name='hojadevidaotrosactivos',
            name='id_articulo',
            field=models.ForeignKey(db_column='T067Id_Articulo', on_delete=django.db.models.deletion.CASCADE, to='almacen.catalogobienes'),
        ),
        migrations.AlterField(
            model_name='hojadevidavehiculos',
            name='id_articulo',
            field=models.ForeignKey(blank=True, db_column='T066Id_Articulo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.catalogobienes'),
        ),
        migrations.AlterField(
            model_name='programacionmantenimientos',
            name='id_articulo',
            field=models.ForeignKey(db_column='T069Id_Articulo', on_delete=django.db.models.deletion.CASCADE, to='almacen.catalogobienes'),
        ),
        migrations.AlterField(
            model_name='registromantenimientos',
            name='cod_estado_final',
            field=models.ForeignKey(db_column='T070Cod_EstadoFinal', on_delete=django.db.models.deletion.CASCADE, related_name='cod_estado_final_Registro', to='almacen.catalogobienes'),
        ),
        migrations.AlterField(
            model_name='registromantenimientos',
            name='id_articulo',
            field=models.ForeignKey(db_column='T070d_Articulo', on_delete=django.db.models.deletion.CASCADE, related_name='id_articulo_Registro', to='almacen.catalogobienes'),
        ),
        migrations.DeleteModel(
            name='Articulos',
        ),
    ]
