# Generated by Django 4.1.3 on 2022-12-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudesconsumibles',
            name='fecha_aprobacion_responsable',
            field=models.DateTimeField(blank=True, db_column='T081fechaAprobacionResponsable', null=True),
        ),
    ]
