# Generated by Django 4.1.3 on 2022-12-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itementradaalmacen',
            unique_together={('id_entrada_almacen', 'id_bien')},
        ),
    ]
