# Generated by Django 4.1.3 on 2022-12-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_entradasalmacen_itementradaalmacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha_ingreso',
            field=models.DateTimeField(blank=True, db_column='T062fechaIngreso', null=True),
        ),
    ]
