# Generated by Django 4.1.3 on 2022-12-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
        ('almacen', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionmantenimientos',
            name='id_persona_solicita',
            field=models.ForeignKey(blank=True, db_column='T069Id_PersonaSolicita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_solicita_programacion', to='seguridad.personas'),
        ),
        migrations.AlterField(
            model_name='solicitudesconsumibles',
            name='id_persona_solicita',
            field=models.ForeignKey(db_column='T081Id_PersonaSolicita', on_delete=django.db.models.deletion.CASCADE, related_name='persona_solicita_solicitud', to='seguridad.personas'),
        ),
        migrations.AlterField(
            model_name='solicitudesconsumibles',
            name='id_unidad_para_la_que_solicita',
            field=models.ForeignKey(db_column='T081Id_UnidadParaLaQueSolicita', on_delete=django.db.models.deletion.CASCADE, related_name='unidad_para_la_que_solicita', to='almacen.unidadesorganizacionales'),
        ),
    ]
