# Generated by Django 4.1.3 on 2022-12-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudesconsumibles',
            old_name='id_solicitud_consumible',
            new_name='id_solicitud_consumibles',
        ),
    ]
