# Generated by Django 4.1.3 on 2022-12-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionmantenimientos',
            name='fecha_programada',
            field=models.DateField(blank=True, db_column='T069fechaProgramada', null=True),
        ),
    ]
