# Generated by Django 4.1.3 on 2022-12-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itementradaalmacen',
            options={'verbose_name': 'Items entrada de Almacen', 'verbose_name_plural': 'Items de Entradas de Almacen'},
        ),
    ]
