# Generated by Django 4.1.3 on 2022-12-09 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itementradaalmacen',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itementradaalmacen',
            name='porcentaje_iva',
            field=models.ForeignKey(db_column='T064porcentajeIVA', default=1, on_delete=django.db.models.deletion.CASCADE, to='almacen.porcentajesiva'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradasalmacen',
            name='numero_entrada_almacen',
            field=models.PositiveIntegerField(db_column='T063nroEntradaAlmacen'),
        ),
        migrations.AlterField(
            model_name='itementradaalmacen',
            name='cod_estado',
            field=models.CharField(choices=[('O', 'Óptimo'), ('D', 'Defectuoso'), ('A', 'Averiado')], db_column='T064Cod_Estado', default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='itementradaalmacen',
            name='id_porcentaje_iva',
        ),
    ]
