# Generated by Django 4.1.3 on 2022-12-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_alter_itementradaalmacen_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposentradas',
            name='constituye_propiedad',
            field=models.BooleanField(db_column='T061constituyePropiedad', default=False),
        ),
    ]
