# Generated by Django 4.1.1 on 2022-11-28 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
        ('almacen', '0003_alter_tiposactivo_cod_tipo_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposEntradas',
            fields=[
                ('cod_tipo_entrada', models.AutoField(db_column='T061CodTipoEntrada', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T061nombre', max_length=15, unique=True)),
                ('descripcion', models.CharField(db_column='T061descripcion', max_length=255)),
                ('titulo_persona_origen', models.CharField(db_column='T061tituloPersonaOrigen', max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo Entrada',
                'verbose_name_plural': 'Tipos Entradas',
                'db_table': 'T061TiposEntrada',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(db_column='T062IdInventario', editable=False, primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(blank=True, db_column='T062fechaIngreso', null=True)),
                ('numero_doc_origen', models.CharField(blank=True, db_column='T062numeroDocOrigen', max_length=30, null=True)),
                ('valor_ingreso', models.FloatField(blank=True, db_column='T062valorAlIngreso', null=True)),
                ('realizo_baja', models.BooleanField(blank=True, db_column='T062realizoBaja', null=True)),
                ('realizo_salida', models.BooleanField(blank=True, db_column='T062realizoSalida', null=True)),
                ('ubicacion_en_bodega', models.BooleanField(blank=True, db_column='T062ubicacionEnBodega', null=True)),
                ('ubicacion_asignado', models.BooleanField(blank=True, db_column='T062ubicacionAsignado', null=True)),
                ('ubicacion_prestado', models.BooleanField(blank=True, db_column='T062ubicacionPrestado', null=True)),
                ('fecha_ultimo_movimiento', models.DateTimeField(blank=True, db_column='T062fechaUltimoMov', null=True)),
                ('tipo_doc_ultimo_movimiento', models.CharField(blank=True, db_column='T062tipoDocUltimoMov', max_length=5, null=True)),
                ('id_registro_doc_ultimo_movimiento', models.PositiveIntegerField(blank=True, db_column='T062IdRegEnDocUltimoMov', null=True)),
                ('cantidad_entrante_consumo', models.PositiveIntegerField(blank=True, db_column='T062cantidadEntranteConsumo', null=True)),
                ('cantidad_saliente_consumo', models.PositiveIntegerField(blank=True, db_column='T062cantidadSalienteConsumo', null=True)),
                ('cod_estado_activo', models.ForeignKey(blank=True, db_column='T062Cod_EstadoDelActivo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.estadosarticulo')),
                ('cod_tipo_entrada', models.ForeignKey(blank=True, db_column='T062Cod_TipoEntrada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.tiposentradas')),
                ('id_bien', models.ForeignKey(db_column='T062Id_Bien', on_delete=django.db.models.deletion.CASCADE, to='almacen.catalogobienes')),
                ('id_bodega', models.ForeignKey(db_column='T062Id_Bodega', on_delete=django.db.models.deletion.CASCADE, to='almacen.bodegas')),
                ('id_persona_origen', models.ForeignKey(blank=True, db_column='T062Id_PersonaOrigen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_origen', to='seguridad.personas')),
                ('id_persona_responsable', models.ForeignKey(blank=True, db_column='T062Id_PersonaResponsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_responsable', to='seguridad.personas')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventario',
                'db_table': 'T062Inventario',
                'unique_together': {('id_bien', 'id_bodega')},
            },
        ),
    ]
