# Generated by Django 4.1.3 on 2022-12-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_alter_itementradaalmacen_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cod_estado_activo',
            field=models.CharField(blank=True, choices=[('O', 'Óptimo'), ('D', 'Defectuoso'), ('A', 'Averiado')], db_column='T062Cod_EstadoDelActivo', max_length=1, null=True),
        ),
    ]
