# Generated by Django 4.1.3 on 2022-12-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_alter_programacionmantenimientos_fecha_programada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registromantenimientos',
            name='id_reg_doc_anterior_mov',
        ),
        migrations.RemoveField(
            model_name='registromantenimientos',
            name='tipo_doc_anterior_mov',
        ),
    ]
