# Generated by Django 4.1.3 on 2022-12-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_alter_solicitudesconsumibles_fecha_aprobacion_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudesconsumibles',
            name='fecha_anulacion_solicitante',
            field=models.DateTimeField(blank=True, db_column='T081fechaAnulacionSolicitante', null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesconsumibles',
            name='fecha_cierre_solicitud',
            field=models.DateTimeField(blank=True, db_column='T081fechaCierreSolicitud', null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesconsumibles',
            name='fecha_rechazo_almacen',
            field=models.DateTimeField(blank=True, db_column='T081fechaRechazoAlmacen', null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesconsumibles',
            name='fecha_solicitud',
            field=models.DateTimeField(db_column='T081fechaSolicitud'),
        ),
    ]
